"""Recognition of conversational openers that are not questions.

"hi." was being answered with "I don't have enough information in the knowledge
base to answer that", which is true but useless: a greeting is not a failed
lookup, and reporting it as one teaches the user that the bot is broken when it
is working correctly.

Three rules keep this from becoming a hole in the grounding guarantee:

1. **Whole-string matching only.** The normalised input must be a greeting and
   nothing else. "hi, what is the return policy?" is a question with a greeting
   attached and goes down the normal retrieval path, because substring matching
   here would silently swallow real questions.
2. **The replies assert nothing.** They make no claim about policy, and no claim
   about what the documents contain, so a different corpus cannot make them
   wrong. Nothing here is generated by the model.
3. **No knowledge is claimed or denied.** This path is reported as its own
   outcome rather than as a knowledge-base miss, so `insufficient_context`
   continues to mean exactly one thing: the documents could not answer this.
"""

from __future__ import annotations

import re
from typing import Optional

from app.config import settings

# Answer kinds. `grounded` is an answer built from retrieved chunks,
# `out_of_scope` is the honest refusal, `small_talk` is this path.
ANSWER_GROUNDED = "grounded"
ANSWER_OUT_OF_SCOPE = "out_of_scope"
ANSWER_SMALL_TALK = "small_talk"

GREETING_REPLY = (
    f"Hello. Ask a question about {settings.knowledge_domain} and I will answer "
    "from it, or tell you plainly if it is not covered."
)
THANKS_REPLY = "You're welcome. Ask another question whenever you need to."
FAREWELL_REPLY = "Goodbye."

_GREETINGS = frozenset(
    {
        "hi",
        "hii",
        "hiya",
        "hey",
        "heya",
        "hello",
        "hallo",
        "yo",
        "hi there",
        "hey there",
        "hello there",
        "good morning",
        "good afternoon",
        "good evening",
        "greetings",
        "howdy",
    }
)

_THANKS = frozenset(
    {
        "thanks",
        "thank you",
        "thankyou",
        "thanks a lot",
        "thanks so much",
        "thank you so much",
        "thanks very much",
        "many thanks",
        "cheers",
        "ty",
    }
)

_FAREWELLS = frozenset(
    {
        "bye",
        "byebye",
        "bye bye",
        "goodbye",
        "good bye",
        "see you",
        "see ya",
        "good night",
        "goodnight",
    }
)

# Keep letters, digits and single spaces. Trailing punctuation and emphasis are
# what make "hi." and "hi!!!" different strings from "hi" to a set lookup.
_STRIP = re.compile(r"[^a-z0-9\s]+")
_SPACES = re.compile(r"\s+")


def _normalise(text: str) -> str:
    return _SPACES.sub(" ", _STRIP.sub(" ", (text or "").lower())).strip()


def small_talk_reply(question: str) -> Optional[str]:
    """Return a reply if the input is purely social, otherwise None.

    None is the signal to carry on with retrieval, so anything unrecognised is
    treated as a real question. That is the safe direction to fail in: a missed
    greeting costs a slightly stiff answer, while a question mistaken for a
    greeting would go unanswered.
    """
    normalised = _normalise(question)
    if not normalised:
        return None

    if normalised in _GREETINGS:
        return GREETING_REPLY
    if normalised in _THANKS:
        return THANKS_REPLY
    if normalised in _FAREWELLS:
        return FAREWELL_REPLY
    return None
